branch-defaults:
  develop:
    environment: development
environment-defaults:
  development:
    branch: null
    repository: null
global:
  application_name: backend
  default_ec2_keyname: development
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on
    64bit Amazon Linux/2.12.2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
