# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[(b'admin', b'admin'), (b'regular', b'regular')], max_length=20)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
